/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Dao.DaoCompte;
import Dao.DaoAdmin;
import Dao.DaoReceptionniste;
import Dao.DaoDentiste;
import Metier.CompteModel;
import java.sql.ResultSet;
/**
 *
 * @author Yashida
 */
public class AListeEmployes extends javax.swing.JPanel {

    DaoCompte DCompte = new DaoCompte();
    DaoAdmin DAdmin = new DaoAdmin();
    DaoReceptionniste DRecep = new DaoReceptionniste();
    DaoDentiste DDent = new DaoDentiste();
    
    public AListeEmployes() {
        initComponents();
        AffichageAdmin();
    }
    
//    String S = combo.getSelectedItem();
    
          
    public void AffichageAdmin() {
        ResultSet Rs = DAdmin.Afficher();
        tableEmploye.setModel(new CompteModel(Rs));   
    }
    public void AffichageReceptionniste() {
        ResultSet Rs = DRecep.Afficher();
        tableEmploye.setModel(new CompteModel(Rs));   
    }
    public void AffichageDentiste() {
        ResultSet Rs = DDent.Afficher();
        tableEmploye.setModel(new CompteModel(Rs));   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmploye = new javax.swing.JTable();
        jComboBoxChoixEmploye = new javax.swing.JComboBox<>();
        panelModifier = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        panelSupprimer = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        tableEmploye.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prénom", "CIN", "Login", "Sexe", "Date de Naissance", "Téléphone", "E-mail", "Date d'embauche"
            }
        ));
        jScrollPane1.setViewportView(tableEmploye);

        jComboBoxChoixEmploye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrateurs", "Dentistes", "Réceptionnistes" }));
        jComboBoxChoixEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixEmployeActionPerformed(evt);
            }
        });

        panelModifier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelModifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelModifier.setPreferredSize(new java.awt.Dimension(120, 30));
        panelModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelModifierMouseClicked(evt);
            }
        });

        jLabel19.setText("Modifier");

        javax.swing.GroupLayout panelModifierLayout = new javax.swing.GroupLayout(panelModifier);
        panelModifier.setLayout(panelModifierLayout);
        panelModifierLayout.setHorizontalGroup(
            panelModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModifierLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        panelModifierLayout.setVerticalGroup(
            panelModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        panelSupprimer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelSupprimer.setPreferredSize(new java.awt.Dimension(120, 30));
        panelSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSupprimerMouseClicked(evt);
            }
        });

        jLabel24.setText("Supprimer");

        javax.swing.GroupLayout panelSupprimerLayout = new javax.swing.GroupLayout(panelSupprimer);
        panelSupprimer.setLayout(panelSupprimerLayout);
        panelSupprimerLayout.setHorizontalGroup(
            panelSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupprimerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSupprimerLayout.setVerticalGroup(
            panelSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jComboBoxChoixEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(panelModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(panelSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxChoixEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxChoixEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixEmployeActionPerformed
        // if var = receptionneist faire afficher recep ...
        String S = (String)jComboBoxChoixEmploye.getSelectedItem();
        if (S=="Dentistes") AffichageDentiste();
        if (S=="Réceptionnistes") AffichageReceptionniste();
        if (S=="Administrateurs") AffichageAdmin();
    }//GEN-LAST:event_jComboBoxChoixEmployeActionPerformed

    private void panelModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelModifierMouseClicked
                  int row = tableEmploye.getSelectedRow();
                    if (row != -1) { 
                    String ID_EMPLOYE=tableEmploye.getValueAt(row, 0).toString();
                    String LOGIN=tableEmploye.getValueAt(row, 1).toString();
                    String CIN=tableEmploye.getValueAt(row, 2).toString();
                    String NOM=tableEmploye.getValueAt(row, 3).toString();
                    String PRENOM=tableEmploye.getValueAt(row, 4).toString();
                    String SEXE=tableEmploye.getValueAt(row, 5).toString();
                    String TELEPHONE=tableEmploye.getValueAt(row, 6).toString();
                    String EMAIL=tableEmploye.getValueAt(row, 7).toString();
                    String DATE_NAISSANCE=tableEmploye.getValueAt(row, 8).toString();
                    String DATE__D_EMBAUCHE=tableEmploye.getValueAt(row, 9).toString();

                    }
     
    }//GEN-LAST:event_panelModifierMouseClicked

    private void panelSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSupprimerMouseClicked
        int row = tableEmploye.getSelectedRow();
        if (row != -1) {String ID_EMPLOYE=tableEmploye.getValueAt(row, 0).toString();
                        String LOGIN=tableEmploye.getValueAt(row, 1).toString();
            String S = (String)jComboBoxChoixEmploye.getSelectedItem();
             if (S=="Dentistes") {  DDent.Supprimer(ID_EMPLOYE); 
                                    DCompte.Supprimer(LOGIN);
                                    AffichageDentiste();
             }
             if (S=="Réceptionnistes") { DRecep.Supprimer(ID_EMPLOYE);
                                         DCompte.Supprimer(LOGIN);
                                         AffichageReceptionniste();}
             if (S=="Administrateurs") { DAdmin.Supprimer(ID_EMPLOYE);
                                         DCompte.Supprimer(LOGIN);
                                         AffichageAdmin();}
            }
    
    }//GEN-LAST:event_panelSupprimerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxChoixEmploye;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelModifier;
    private javax.swing.JPanel panelSupprimer;
    private javax.swing.JTable tableEmploye;
    // End of variables declaration//GEN-END:variables
}
