/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Dao.DaoOrdonance;
import Metier.OrdonanceModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hatim
 */
public class DOrdonancePan extends javax.swing.JPanel {
  DaoOrdonance D = new DaoOrdonance();
  String IdD="12";
    /**
     * Creates new form DOrdonancePan
     */
    public DOrdonancePan() {
        initComponents();
        Afficher();
        NombreOrdonnance();
    }
    public void Afficher(){
        ResultSet Res = D.Read(IdD);
        Odonnances.setModel(new OrdonanceModel(Res));
    }
        public void NombreOrdonnance()
    {
        
        try {
            ResultSet nbrOp = D.NombreOrd(IdD);
            nbrOp.next();
             this.nbrOp.setText(nbrOp.getString(1));
        } catch (SQLException ex) {
            Logger.getLogger(DOperation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Odonnances = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nbrOp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Odonnances.setAutoCreateRowSorter(true);
        Odonnances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        Odonnances.setGridColor(new java.awt.Color(255, 255, 255));
        Odonnances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OdonnancesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Odonnances);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Mes Ordonnances");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Nombre total d'ordonnances prescrites : ");

        nbrOp.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nbrOp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 297, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(296, 296, 296))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nbrOp))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OdonnancesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OdonnancesMouseClicked
       try{
        if (evt.getClickCount() == 2) {
            int row = Odonnances.getSelectedRow();
            if (row != -1) {
               String Nom = Odonnances.getValueAt(row, 0).toString();
               String date = Odonnances.getValueAt(row,2).toString();
               String pdfname="Ordonnace"+Nom+date+".pdf";
               System.out.println(pdfname);
               Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "
                    +"C:\\Users\\hatim\\OneDrive\\S1\\JAVA\\TDs\\projet 2018\\gestclicks2\\"+pdfname) ;
               System.out.println("done");
            }
        }
            }
            catch(Exception e){
                System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_OdonnancesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Odonnances;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nbrOp;
    // End of variables declaration//GEN-END:variables
}
